routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminDetailController;
use App\Livewire\Admin\Details;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


//Route::namespace('\App\Http\Controllers\Admin')->prefix('admin')->group(function (){
//    Route::resource('admin' , AdminController::class);
//});


Route::name('admin.')->prefix('admin')->group(function (){
    Route::middleware('Admin')->group(function (){
        Route::namespace('\App\Http\Controllers\Admin')->group(function (){
            Route::view('/dashboard' , 'admin.index')->name('dashboard');
//            Route::resource('/details' , AdminDetailController::class);
        });

        Route::namespace('\App\Livewire\Admin')->group(function (){
            Route::get('createAdmin' , function (){
                return view('admin.admins.create');
 });

            Route::get('admins' , function (){
                return view('admin.admins.index' , ['name' => 'admins']);
            });

            Route::resource('details' , Details::class);
//            Route::resource('show_details' , ShowAdminDetails::class);
//            Route::resource('show_details' , ShowAdminDetails::class);
        });


    });


    require __DIR__.'/admin_auth.php';
});



//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth', 'verified'])->name('dashboard');
//
//Route::middleware('auth')->group(function () {
//    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
//});

routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Route::get('/', function () {
//    return view('admin.auth.');
//});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Livewire/Admin/AdminSearch.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class AdminSearch extends Component
{
    public function render()
    {
        return view('livewire.admin.admin-search');
    }
}

app/Livewire/Admin/Details.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class Details extends Component
{

    public function show()
    {
        return view('livewire.admin.details');
    }
    public function render()
    {
        return view('livewire.admin.details');
    }
}

app/Livewire/Admin/EditAdminDetails.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class EditAdminDetails extends Component
{
    public function render()
    {
        return view('livewire.admin.edit-admin-details');
    }
}

app/Livewire/Admin/Model.php
<?php

namespace App\Livewire\Admin;

use LivewireUI\Modal\ModalComponent;

class Model extends ModalComponent
{
    public static function modalMaxWidth(): string
    {
        // 'sm'
        // 'md'
        // 'lg'
        // 'xl'
        // '2xl'
        // '3xl'
        // '4xl'
        // '5xl'
        // '6xl'
        // '7xl'
        return '4xl';
    }
    public function render()
    {
        return view('livewire.admin.model');
    }
}

app/Livewire/Admin/RegisterForm.php
<?php

namespace App\Livewire\Admin;

use Livewire\Component;

class RegisterForm extends Component
{
    public function render()
    {
        return view('livewire.admin.register-form');
    }
}

app/Livewire/Admin/SearchAdmin.php
<?php

namespace App\Livewire\Admin;

use App\Models\admin\Admin;
use Livewire\Component;

class SearchAdmin extends Component
{
    public $search = '';
    public function render()
    {

        return view('livewire.admin.admins' , [
            'searchs' => Admin::search($this->search)
        ]);
    }
}

app/Livewire/Admin/ShowAdminDetails.php
<?php

namespace App\Livewire\Admin;

use App\Models\admin\Admin;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class ShowAdminDetails extends Component
{
//    public function render()
//    {
////        dd('render');
//        return view('livewire.admin.admin-details');
//    }



    public function show()
    {
        $getId = Admin::where('id' , Auth::guard('admin')->user()->id)->first();
        return view('livewire.admin.show-admin-details' , ['getId' => $getId]);
    }

    public function edit()
    {
        $getId = Admin::where('id' , Auth::guard('admin')->user()->id)->first();
        return view('livewire.admin.admin-details' , ['getId' => $getId]);
    }

}

app/Livewire/Admin/admin/Create.php
<?php

namespace App\Livewire\Admin\Admin;

use App\Models\admin\Admin;
use Livewire\Attributes\Rule;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class Create extends Component
{
    use WithFileUploads;
    use WithPagination;

//    #[Rule('image|max:1024')]
#[Rule('required|max:30|min:3')]
    public $name;
    #[Rule('required|email|max:30|unique:admins')]

    public $email;
#[Rule('required|min:6')]
    public $password;
    #[Rule('required|min:6')]
    public $title;
//    #[Rule('required')]
    public $status;
    #[Rule('required')]
    public $phone;
//    #[Rule('required|max:30|min:6|file')]
//    public $image;

    public function render()
    {
        return view('livewire.admin.admin.create');
    }
    public function save()
    {
        $this->validate();
        Admin::create(
            $this->only(['name', 'phone' ,'email', 'password' , 'title' , 'status'])
        );
request()->session()->flash('status' , 'added');
        return $this->redirect('/admin/admins');
    }

}

app/Livewire/Admin/admin/index.php
<?php

namespace App\Livewire\Admin\admin;

use App\Models\admin\Admin;
use Illuminate\Support\Facades\Request;
use Livewire\Attributes\Rule;
use Livewire\Component;
use Livewire\WithPagination;
use function view;

class index extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $search='';
    public $editId;
    #[Rule('required|max:30|min:3')]
    public $name;
    #[Rule('required|email|max:30|unique:admins')]
    public $email;
    #[Rule('required|min:6')]
    public $password;
    #[Rule('required|min:6')]
    public $title;
//    #[Rule('required')]
    public $state;
    public $type;
    #[Rule('required')]
    public $phone;
    public $page = '';


        public function editForm($admin)
        {
            $admin = Admin::find($admin);
            $this->editId = $admin->id;
            $this->name = $admin->name;
            $this->email = $admin->email;
            $this->title = $admin->title;
            $this->type = $admin->type;
            $this->phone = $admin->phone;
            $this->state = $admin->state;
            return view('livewire.admin.admin.index');
        }
        public function cancelEdit()
        {
            $this->reset('editId' , 'name' , 'email' , 'title' , 'type' , 'phone' , 'status');
        }
        public function update()
                {
            //        $this->validate();
                    $admin = Admin::find($this->editId);
                    $admin->update(
                        [
                            'name' => $this->name,
                            'email' => $this->email,
                            'phone' => $this->phone,
                            'type' => $this->type,
                            'status' => $this->state,
                            'title' => $this->title,
                        ]
                    );

                    request()->session()->flash('status' , 'تم تحديث البيانات');
                    return $this->redirect('/admin/admins');


                }
        public function delete($id){
                    try {
                        Admin::findOrFail($id)->delete();
                    }
                    catch (\Exception $exception)
                    {
                        request()->session()->flash('status' , 'تم الحذف');
                        return;
                    }
            }
        public function toggle($id)
            {
                $checked = Admin::find($id);
                $checked->state = !$checked->state;
                $checked->save();
            }

        public function render()
            {
                return view('livewire.admin.admin.index' , [
                    'admins' => Admin::where('name' , 'like' , '%' . $this->search . '%')->orderBy('id','asc')->paginate(5),
                ]);
            }
}

resources/views/livewire/admin/details.blade.php
<div>
    {{-- Success is as dangerous as failure. --}}
</div>

resources/views/livewire/admin/model.blade.php
    <div class="">
        <x-modal>
            <x-slot name="title">
                Hello World
            </x-slot>

            <x-slot name="content" class="">
                Hi! 👋
            </x-slot>

            <x-slot name="buttons">
                Buttons go here...
            </x-slot>
        </x-modal>
    </div>

resources/views/livewire/admin/register-form.blade.php
<div>
   </div>

resources/views/livewire/admin/search-admin.blade.php
<div>
    {{-- Stop trying to control. --}}
</div>

resources/views/livewire/admin/show-admin-details.blade.php
<div>
    @extends('admin.app')
   @section('content')
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <section>
                    <div class="container py-5">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="card mb-4">
                                    <div class="card-body text-center">
                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                                             class="rounded-circle img-fluid" style="width: 183px;">

                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="card mb-4">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <p class="mb-0">الاسم</p>
                                            </div>
                                            <div class="col-sm-9">
                                                <p class="text-muted mb-0">
                                                    {{$getId->name}}

                                                </p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <p class="mb-0">البريد</p>
                                            </div>
                                            <div class="col-sm-9">
                                                <p class="text-muted mb-0">
                                                    {{$getId->email}}
                                                </p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <p class="mb-0">موبايل</p>
                                            </div>
                                            <div class="col-sm-9">
                                                <p class="text-muted mb-0">
                                                    {{$getId->phone}}
                                                </p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <p class="mb-0">العنوان</p>
                                            </div>
                                            <div class="col-sm-9">
                                                <p class="text-muted mb-0">
                                                    {{$getId->title}}

                                                </p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <p class="mb-0">العمليات</p>
                                            </div>
                                            <div class="col-sm-9">
                                                <p class="text-muted mb-0">
                                                    <a class="btn btn-danger" href="{{route('admin.details.edit' , $getId)}}">تعديل</a>
                                                </p>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
    @endsection
       @section('title' , 'N-SHOP')
</div>